### PR TITLE
#5: refactor: require => expect

### LINKED ISSUE #5: `require` => `expect`?
**Describe the bug**
The use of `require` as an argument to `checkDT` raises lintr issues and in general invites function name collisions.

**Expected behavior**
Alternative argument names to preclude the lintr issues. Suggest: `expect` - other options?

### PR DESCRIPTION
**Pull request by pearsonca**
## Description

This PR closes #5.

The argument `require` is replaced with `expect`

## Checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [X] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [X] I have tested my changes locally.
- [X] I have added or updated unit tests where necessary.
- [X] I have updated the documentation if required.
- [X] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

File: R/checkDT.R [hunk 1]
```diff
@@ -4,7 +4,7 @@
 #'
 #' @param data a `data.table`, e.g. as a product of [coerceDT()]
 #'
-#' @param require Optional; if `NULL` (the default), there are no required
+#' @param expect Optional; if `NULL` (the default), there are no required
```
Comment (seabbs) [inline R/checkDT.R:7]:
```suggestion
#' @param expect Optional; if `NULL` (the default), there are no expected
```

**Review by seabbs — APPROVED** [review]
This looks good but I think we should also reword the docs to match the new argument.
